# conf/config.yaml

# The 'defaults' list specifies the configuration files to compose.
# By using the syntax 'data: data' and 'model: model', we are telling Hydra
# to create a 'data' group and a 'model' group in the final config object,
*and* to load the contents of 'data.yaml' and 'model.yaml' into them.
# This creates the nested structure like `config['data']['zones']` that the
# Python code expects.
defaults:
  - data: data   # Creates a 'data' key and loads data.yaml into it.
  - model: model # Creates a 'model' key and loads model.yaml into it.
  - _self_

# App-level configurations can be defined here
app_name: "RedShield AI: Phoenix v4.1"
forecast_horizons_hours: [0.5, 1, 3, 6, 12, 24, 72]
mapbox_api_key: ${oc.env:MAPBOX_API_KEY, null}
