defaults:
  - data: data
  - model: model
  - _self_

app_name: "RedShield AI: Phoenix v4.1"
forecast_horizons_hours: [0.5, 1, 3, 6, 12, 24, 72]
mapbox_api_key: ${oc.env:MAPBOX_API_KEY, null}

ml_models:
  tcnn_name: "phoenix_tcnn"
