defaults:
  - data: _self_   # Include all keys from data.yaml at this top level
  - model: _self_  # Include all keys from model.yaml at this top level

# App-level configurations can be defined here
app_name: "RedShield AI: Phoenix v4.1"
forecast_horizons_hours: [0.5, 1, 3, 6, 12, 24, 72]
mapbox_api_key: ${oc.env:MAPBOX_API_KEY, null}
